It5
garcia50/little-shop-redux pull request #24
Opened 2018-01-26 15:19 UTC by annaroyer

Everything should be pretty much good to go it5/it6. BUT what do you guys think about the db seed for items? The csv file is storing them as unit price so initially I divided that by 100 in the seed file before storing it in the database. But now I'm thinking that maybe we want to store price in unit price form? In which case we would have to change the price that users entered inside of our model before creating each new record. Thoughts?

2018-01-26 16:17 UTC, lnchambers requested changes

2018-01-26 16:17 UTC, lnchambers commented on app/models/item.rb
> +  validates_presence_of :title, :description, :price, :image, presence: true
validates_presence_of already validates presence: true

2018-01-26 16:17 UTC, lnchambers commented on db/seeds.rb
> +    price = (row[:unit_price].to_f / 100).round(2)
Maybe we should consider using BigDecimal. Thoughts?

2018-01-26 16:18 UTC, lnchambers commented
Hey Ali, Ilana, we would like some feedback on our items pricing. We are currently converting the price to dollars while seeding, but we are thinking about using BigDecimal instead. Thoughts?

2018-01-26 21:21 UTC, AliSchlereth commented
@lnchambers @annaroyer @garcia50 Great question! You'll want to store the data in the same format it comes in as. Changing the format would mutate the data and potentially introduce minute changes which could significantly impact calculations, etc down the road.

2018-01-26 21:35 UTC, AliSchlereth reviewed
@lnchambers @annaroyer @garcia50 Great question! You'll want to store the data in the same format it comes in as. Changing the format would mutate the data and potentially introduce minute changes which could significantly impact calculations, etc down the road.

2018-01-27 00:52 UTC, lnchambers approved these changes

2018-01-27 22:42 UTC, merged